# Site settings
title: Maxime TINEL
twitter_username: MaximeTinel
name: Maxime TINEL
location: La Ciotat, FR

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: LinkedIn
   url: http://fr.linkedin.com/in/maximetinel
 - title: Viadeo
   url: http://www.viadeo.com/fr/profile/maxime.tinel

#Any buzzword skills you want to include
skills:
 - Scala
 - sbt
 - Akka
 - Apache Spark
 - Machine Learning
 - Java
 - Maven
 - Spring Boot
 - JSF
 - JPA
 - SQL
 - REST
 - Docker
 - Tech Architecture
                                    

#Blogfeed is optional - including this will add JS to call the feed and populate blog list
#blogfeed: http://automateddeveloper.blogspot.com/feeds/posts/default?alt=rss

#Work experience is required
roles:
 - title: Software Developper
   start: 2017
   end: Ongoing
   employer: WakeonWeb
   description: WakeOnWeb is a service company in the digital sector, specializing in the design and development of specific WEB applications for innovative companies. I am responsible for developing the company's Big Data and Machine Learning skills.
 - title: Software Developper
   start: 2014
   end: 2017
   employer: Net Informatique Services
   description: Created in 1995, NIS has established itself as a leader in the indirect distribution of digital security products. During its growth, the company opened up to the IOT and french health care (Ingenico hardware reader, and its own software reader) market. In this context, I have developped an application to manage a Cryptographic USB key from Gemalto (IDBridge K3000), allowing the USB key to be securely (with a HSM) personalized, and remotely updated. I also had to support, a cloud / on-prem authentication solution (Safenet Authentication Service), and health care solutions.

#Education is required
education:
 - level: Bachelor (EQF L6 / French NQF L2)
   date: 2013
   subject: Concepteur Développeur Informatique
   school: AFPA of Saint-Étienne-du-Rouvray (FR)
 - level: Undergraduate technician certificate (EQF L5 / French NQF L3)
   date: 2000
   subject: Informatique Industrielle
   school: Lycée Modeste Leroy of Evreux (FR)
 - level: Technological baccalaureate (EQF L4 / French NQF L4)
   date: 1998
   subject: Sciences et technologies industrielles génie Électrotechnique
   school: Lycée Pablo Néruda of Dieppe

#This section is optional (as is the image link below)
moocs:
 - plateform: Coursera
   profileurl: https://www.coursera.org/user/610a4f6a81defd283eaa9307263410f8
   courses:
    - title: Functional Programming Principles in Scala
      link: https://www.coursera.org/course/progfun
      optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/progfun/small-icon.hover.png
      date: May, 2018
 - plateform: OpenClassrooms
   profileurl: https://openclassrooms.com/fr/membres/maxime-tinel
   courses:
    - title: Initiez-vous au machine learning
      link: https://openclassrooms.com/fr/courses/initiez-vous-au-machine-learning/
      optionalimage: https://udemy-images.udemy.com/course/240x135/1382702_a351.jpg
      date: September, 2018

#List of interesting Github repo/projects to include - optional
#github:

#Stackoverflow flair is optional
#stackoverflow:
#   profileurl: http://stackoverflow.com/users/4248608/maxoute
#   flairimageurl: http://stackoverflow.com/users/flair/4248608.png

#Mobile apps section is optional
#apps:

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <strong>JVM</strong>: I am experienced in a variety of Java API’s and frameworks. I have recently worked with Spring 4, Spring Boot, JPA (Hibernate), JCA / JCE in addition to others.  In my current role Scala is the primary language used - and I am familiar with many of the languages features and quirks. <br/><br/>
   <strong>Web Development</strong>: My server side web development experience has largely been based on JSF with PrimeFaces framework (although current role uses Spring MVC). I have also worked with some client side technology, having used jQuery.<br/><br/>
   <strong>Development Control</strong>: I have a good knowledge of application life-cycle management and have worked with SVN, Git, Maven, sbt, Sonar and Jenkins. I have experience with an array of testing tools and technologies.<br/><br/>
